### ISSUE TITLE
feature/roadmap request: Responsive UI

### ISSUE THREAD

**Issue by haysclark** [jenkins-x/jx-pipelines-visualizer#28]
It would be great to know if this project intends to encompass Responsive UI or if such matters are outside the scope of the project. Naturally, if Responsive UI is intended, documenting what frameworks to utilize would ideal.

**Comment by florianorpeliere** [comment]
Hello @haysclark, that's a good question. 

To be honest, I didn't plan to do responsive web design right away (at least for mobile and tablet). Because in my opinion, this visualizer is mainly used on desktop. But maybe I'm wrong, and in this case, I'll add this functionality with pleasure 😉. Maybe you're basically talking about the different sizes for the desktops. In this case, indeed, I will look into the matter. 

Regarding the framework, I think it is possible to do responsive web design without a framework. I have to assess the need we have.

Furthermore, it is true that there is no defined roadmap for the moment. I'll quickly provide one. 
For example, there are plans to change the UI build system to something more "modern" 😄 .

Have a good day !

**Comment by jstrachan** [comment]
incidentally I find `jx-pipelines-visualizer` works much better on my iPhone than the old `jxui` ever did despite having a responsive design ;)

the main time I use `jx-pipelines-visualizer` on my phone is to look at 1 pipeline log usually; which renders nicely right now

**Comment by haysclark** [comment]
/close I agree with @jstrachan as JX3 has this covered and most users will be upgrading.

Screenshot of the more Responsive UI provided in jx3: 
![image](https://user-images.githubusercontent.com/138324/116130981-accbe380-a680-11eb-97e6-2ac6314b3f44.png)

**Comment by haysclark** [comment]
I agree with @jstrachan as JX3 has this covered and most users will be upgrading.

Screenshot of the more Responsive UI provided in jx3:
![image](https://user-images.githubusercontent.com/138324/116131412-38de0b00-a681-11eb-8b65-ecfe707442f0.png)
