### ISSUE TITLE
archived logs don't work if using `jx dash`

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx-pipelines-visualizer#54]
when we run `jx dash` it opens the dashboard URL using http://username:password@whatever.nip.ip - which is a great way to setup the basic auth for users without them having to lookup secrets and copy/paste things.

It seems that the loading of archive logs never triggers in this case - this is never invoked so logs are never queried: https://github.com/jenkins-x/jx-pipelines-visualizer/blob/master/web/static/archived_logs/index.js#L1

I guess its related to basic auth + `XMLHttpRequest`?

Whats odd is if you open a browser window via http://whatever.nip.ip  (without the user/pwd) it all works great.

So not totally sure what to do about this; its definitely related to the use of XMlHttpRequest making a second query for the logs in archive mode.

One idea is to get `jx dash` to open 2 URLs; the first one with the user/pwd and the second without it (the real one to use ;) - not sure really - there must be a better way?

I guess the real fix is to really use OAuth?

**Comment by vbehar** [comment]
@florianorpeliere do you have an idea? what's strange is that the requests to get the live logs (via eventsource) or stored logs (via fetch) works well. maybe we could just rewrite this part to use `fetch` as we do for the stored logs?

**Comment by jstrachan** [comment]
@vbehar yeah - its wacky live logs work fine - did wonder about detecting user/pwd in the URL and redirecting or something; but can't seem to find the user/pwd in the URL in go code so not sure really

**Comment by jstrachan** [comment]
things work great when not using `jx dash` - its just a shame as thats such a lovely UX for folks to easily open the dashboard

**Comment by florianorpeliere** [comment]
@vbehar I'm not sure fetch changes anything, I'll take a look at this. In any case, replacing this code with a fetch is a good thing in all cases ;)

**Comment by jstrachan** [comment]
@florianorpeliere happy to help too if you need a hand - just not sure what to do ;)

**Comment by jstrachan** [comment]
its wacky live logs work perfectly + its just archived logs that don't work. would it be easy to use the same mechanism for live and archive logs?

**Comment by florianorpeliere** [comment]
@jstrachan Yes :) I creating a PR to have the same mechanism in both pages

**Comment by florianorpeliere** [comment]
@jstrachan 
Does this fix the problem ? (I hope yes 🤞🏻 )

**Comment by vbehar** [comment]
so @jstrachan tells me he still has the problem. And I think I know why: he's using the /namespaces/jx/pipelineruns/xyz URLs, which retrieve the pipelinerun and then the pipelineactivity (instead of the pipelineactivity directly). pipelineruns usually have a shorter lifetime than the pipelineactivities.
And I guess that the pipelinerun has been garbage collected, and thus we render the archived logs at https://github.com/jenkins-x/jx-pipelines-visualizer/blob/v0.0.74/web/handlers/pipelinerun.go#L95 but without data, this explains why archived logs can't be retrieved.

if I'm right, then we should:
- return a 404 if we can't find the pipelinerun - because we don't have enough information to do anything else
- and we could also update the build controller to store the pipelinerun in the long-term storage - similar to https://github.com/jenkins-x-plugins/jx-build-controller/pull/11 - and then we could retrieve all pipelineruns even if garbage collected.

**Comment by vbehar** [comment]
I think we can close this one now, it has been fixed
